### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by OnkelTem** [yggie/babel-plugin-inline-json-import#16]
Babel 7.

I run transformation as:
```
$ babel src --out-dir js --extensions '.ts' --source-maps`
```

And get this error:

```
TypeError: /project/src/app.ts: Cannot read properties of undefined (reading 'name')
    at /project/node_modules/babel-plugin-inline-json-import/build/index.js:88:51
    at Array.map (<anonymous>)
    at buildObjectPatternFromDestructuredImport (/project/node_modules/babel-plugin-inline-json-import/build/index.js:87:36)
    at determineLeftExpression (/project/node_modules/babel-plugin-inline-json-import/build/index.js:74:12)
    at PluginPass.exit (/project/node_modules/babel-plugin-inline-json-import/build/index.js:33:34)
    at newFn (/project/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/project/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/project/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/project/node_modules/@babel/traverse/lib/path/context.js:109:8)
    at TraversalContext.visitQueue (/project/node_modules/@babel/traverse/lib/context.js:103:16) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```
The code referenced in the error:

```js
function buildObjectPatternFromDestructuredImport(types, node) {
  var properties = node.specifiers.map(function (specifier) {
    var key = types.identifier(specifier.imported.name); // <<<<<<<<<<< 88th line
    var value = types.identifier(specifier.local.name);

    return types.objectProperty(key, value);
  });

  return types.objectPattern(properties);
}
```

Ideas?

**Comment by yggie** [comment]
Hard to say without knowing what the code looks like, do you have a snippet of code you can share that can reproduce the issue? All I can say is that it looks like the code just came across an expected format
